# Copyright (c) 2025 Oleksiy Oleksandrovych Sayankin. All Rights Reserved.
# Refer to the LICENSE file in the root directory for full license details.
spring:
  config:
    import: "classpath:mdds-common.yml"

mdds.result.consumer:
  host: localhost
  port: 8863
server:
  address: ${mdds.result.consumer.host}
  port: ${mdds.result.consumer.port}