# Copyright (c) 2025 Oleksiy Oleksandrovych Sayankin. All Rights Reserved.
# Refer to the LICENSE file in the root directory for full license details.
spring:
  config:
    import: "classpath:mdds-common.yml"

mdds.server:
  host: localhost
  port: 8000
server:
  address: ${mdds.server.host}
  port: ${mdds.server.port}
